sudo: false

language: rust

cache: cargo

branches:
  only:
  - master

rust:
  - 1.47.0

before_install:
  - rustup component add rustfmt

#install:
  # - cargo install --force cargo-make

script:
  #cargo make --makefile make.toml test
  # To improve our cache
  cargo test
