# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v2


      - name: Run a multi-line script
        run: |
          echo "Installing sshpass"
          sudo apt install sshpass
          echo "Connecting to remote machine"
          sshpass -p ${{ secrets.SSH_SECRET }} ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          echo "Geting remote ls"
          ls -la
