name: "Continuous Integration Tests"
on:
  push:
    branches: 
      - 'master'
      - 'hito*'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
      - '**/Vagrantfile'
      - './test-cases.json'
      - './taurus_benh.yml'
      - './openrc.sh'
      - './local.provision'
      - './cc.yaml'
      - './buddy.yml'
      - './benchmark.lua'
      - './.env.example'
      - './.all-contributorsrc'
      - './_config.yml'
      - './client'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # List of possible runners 
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      # Smart Cache for rust
      # https://github.com/Swatinem/rust-cache
    - uses: Swatinem/rust-cache@v1

    - name: Build
      run: cargo build --verbose


    - name: Run tests
      run: cargo test -- --nocapture
