# This is a basic workflow to help you get started with Actions

name: CheckPRBody

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   check_pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Check Body of Pull Request
      uses: JJ/github-pr-contains-action@releases/v2
      with:
        github-token: ${{github.token}}
        bodyContains: "[x]" # Ensures promise will be completed :)
        bodyDoesNotContain: "|" # Ensures Selection between {Feature request, Bug Report, Other} # To improve!
