name: "Crea artefacto con configuración"
on:
  workflow_run:
    workflows: ["Check cc.yaml file"]
    types: completed

jobs:
  sube_config:
    runs-on: ubuntu-latest
    steps:
      - name: Descarga contenidos
        uses: actions/checkout@v2
      - name: Descarga ysh y ejecuta
        run: |
          sudo curl -s -L https://raw.githubusercontent.com/azohra/yaml.sh/v0.2.0/ysh --output /usr/bin/ysh
          sudo chmod +x /usr/bin/ysh
          ysh -v
          .github/workflows/procesa_yaml.sh
      - name: "Sube el fichero"
        uses: actions/upload-artifact@v2
        with:
          name: cc-config
          path: CC_CONFIG

